In [1]:
import pyarrow.parquet as pq
import pandas as pd

In [6]:
trips = pq.read_table("yellow_tripdata_2026-05.parquet")
trips = trips.to_pandas()
trips

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-05-01 00:04:59,2026-05-01 00:32:48,1.0,7.51,1.0,N,138,37,2,35.90,6.00,0.5,0.00,0.0,1.0,45.40,0.0,2.0,0.00
1,2,2026-05-01 00:37:05,2026-05-01 00:59:47,1.0,6.14,1.0,N,138,237,1,27.50,6.00,0.5,9.56,0.0,1.0,49.81,2.5,2.0,0.75
2,1,2026-05-01 00:34:05,2026-05-01 00:54:02,1.0,2.40,1.0,N,249,232,1,19.10,4.25,0.5,3.73,0.0,1.0,28.58,2.5,0.0,0.75
3,1,2026-05-01 00:55:07,2026-05-01 01:02:43,0.0,1.20,1.0,N,232,114,1,9.30,4.25,0.5,3.00,0.0,1.0,18.05,2.5,0.0,0.75
4,7,2026-05-01 00:44:13,2026-05-01 00:44:13,2.0,0.86,1.0,N,140,237,1,7.20,0.00,0.5,2.44,0.0,1.0,14.64,2.5,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4090831,2,2026-05-31 23:35:12,2026-05-31 23:51:04,NaN,5.11,NaN,NaN,74,243,0,17.19,0.00,0.5,0.00,0.0,1.0,18.69,NaN,NaN,0.00
4090832,1,2026-05-31 23:48:01,2026-06-01 00:05:57,NaN,8.80,NaN,NaN,129,130,0,27.98,0.00,0.5,0.00,0.0,1.0,33.48,NaN,NaN,0.00
4090833,2,2026-05-31 23:48:50,2026-06-01 00:03:52,NaN,6.47,NaN,NaN,48,116,0,24.12,0.00,0.5,0.00,0.0,1.0,28.87,NaN,NaN,0.75
4090834,2,2026-05-31 23:23:13,2026-05-31 23:38:35,NaN,2.94,NaN,NaN,113,256,0,18.20,0.00,0.5,0.00,0.0,1.0,22.95,NaN,NaN,0.75
4090835,2,2026-05-31 23:41:51,2026-05-31 23:47:32,NaN,0.83,NaN,NaN,255,112,0,7.02,0.00,0.5,0.00,0.0,1.0,8.52,NaN,NaN,0.00

In [ ]:
trips = pq.read_table("yellow_tripdata_2026-05.parquet")
trips = trips.to_pandas()
trips= trips.sample(n=40000, random_state=42)  # Sample 40,000 rows from the DataFrame
trips

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
182196,2,2026-05-02 18:03:26,2026-05-02 18:08:58,1.0,1.07,1.0,N,236,239,1,7.90,0.0,0.5,2.38,0.0,1.0,14.28,2.5,0.0,0.00
912818,2,2026-05-09 18:17:34,2026-05-09 18:50:28,1.0,4.94,1.0,N,231,142,1,32.40,0.0,0.5,7.43,0.0,1.0,44.58,2.5,0.0,0.75
53506,2,2026-05-01 15:54:42,2026-05-01 16:06:35,1.0,1.44,1.0,N,170,141,1,12.10,0.0,0.5,0.00,0.0,1.0,16.85,2.5,0.0,0.75
3844399,2,2026-05-23 23:02:41,2026-05-23 23:23:02,NaN,3.54,NaN,NaN,234,239,0,26.18,0.0,0.5,0.00,0.0,1.0,30.93,NaN,NaN,0.75
2253303,1,2026-05-22 07:12:39,2026-05-22 07:51:05,1.0,34.90,99.0,N,236,244,1,28.50,0.0,0.5,0.00,0.0,0.0,29.00,0.0,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192726,1,2026-05-12 17:32:50,2026-05-12 17:44:31,1.0,1.70,1.0,N,237,236,1,12.80,5.0,0.5,3.85,0.0,1.0,23.15,2.5,0.0,0.00
2508887,2,2026-05-25 14:23:28,2026-05-25 15:01:48,1.0,13.99,1.0,N,132,226,1,56.20,0.0,0.5,5.00,0.0,1.0,64.70,0.0,2.0,0.00
3057664,2,2026-05-31 01:13:06,2026-05-31 01:22:17,1.0,2.36,1.0,N,263,163,1,12.80,1.0,0.5,3.71,0.0,1.0,22.26,2.5,0.0,0.75
482781,2,2026-05-05 20:43:53,2026-05-05 21:03:08,2.0,2.68,1.0,N,246,229,1,18.40,1.0,0.5,4.83,0.0,1.0,28.98,2.5,0.0,0.75
1439119,2,2026-05-14 18:25:39,2026-05-14 18:47:33,2.0,3.48,1.0,N,140,79,1,21.20,2.5,0.5,8.54,0.0,1.0,36.99,2.5,0.0,0.75

In [ ]:
trips.to_csv("yellow_tripdata_2026-05_sample.csv", index=False)
trips.to_excel("yellow_tripdata_2026-05_sample.xlsx", index=False)